version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && export SECRET_KEY_BASE=`bundle exec rake secret` && rake db:create && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/railsjig
    ports:
      - "80:80"
    depends_on:
      - db